### ISSUE TITLE
Cyrillic languages not supported

### ISSUE THREAD

**Issue by surreum** [angeloashmore/react-use-flexsearch#17]
Does anybody can advice how to create search index with cyrillic symbols. With latin letters search  works fine. I use this plugin in Gatsby JS.

**Comment by yura2100** [comment]
Hello @surreum,

Recently I had the same problem and I found out that there is nothing with react-use-flexsearch.
It is more about flexsearch . [This](https://github.com/nextapps-de/flexsearch/issues/182) helped me to solve the problem.

**Comment by angeloashmore** [comment]
@yura2100 Thanks for sharing! I'm going to close this issue, but @surreum please feel free to reply here if you're still having trouble and I can reopen it.

**Comment by surreum** [comment]
> Hello @surreum,
> 
> Recently I had the same problem and I found out that there is nothing with react-use-flexsearch.
> It is more about flexsearch . [This](https://github.com/nextapps-de/flexsearch/issues/182) helped me to solve the problem.

Thank you yura2100! I'll try to solve it.
